name "gestorpsi"
maintainer "Matheus Fernandes"
maintainer_email "matheus.souza.fernandes@gmail.com"
license "GPL v2"
description "Setup development environment for GestoPSI"
version "0.0.1"

depends "python"
depends "git"
depends "mariadb"